### ISSUE TITLE
The s25fl512s.c file is missing

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/s25fl512s#1]
The s25fl512s.c file is missing here. Or  should the .c file be reused from s25fl128s?

**Comment by RKOUSTM** [comment]
Hi @pavel-a,

Thank you for your report. In order to use the S25FL128S QuadSPI component driver, you only need to use the  [s25fl512s.h](https://github.com/STMicroelectronics/stm32-s25fl512s/blob/main/s25fl512s.h) file, which contains all the definitions of the S25FL512S memory (configuration, instructions and registers). Indeed, this BSP component is supported by the STM32F469I-EVAL board where the s25fl512s.h file is included in the stm32469i_eval_qspi.h file.  You can refer to [this](https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Projects/STM32469I_EVAL/Demonstrations/STemWin) demo on STM32F469I-EVAL to get an idea of haw the QSPI interface is initialized with the BSP_QSPI_Init() function. 

Regarding the point for which you opened the issue, as it is irrelevant, allow me to close the issue. Thank you for your comprehension and thank you again for your report.

With regards,
